tap "aaronraimist/tap"
tap "gcenx/wine"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "teamookla/speedtest"
brew "python@3.9"
brew "harfbuzz"
brew "jpeg-xl"
brew "bash"
brew "node"
brew "bitwarden-cli"
brew "boost"
brew "bottom"
brew "ccache"
brew "chezmoi"
brew "cocoapods"
brew "emacs"
brew "extra-cmake-modules"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "python@3.10"
brew "gobject-introspection"
brew "helix"
brew "htop"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "libolm"
brew "lsd"
brew "mas"
brew "midnight-commander"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "ninja"
brew "openjdk@17"
brew "pipx"
brew "qt"
brew "thefuck"
brew "toot"
brew "tree"
brew "w3m"
brew "weechat"
brew "yetris"
brew "youtube-dl"
brew "yt-dlp"
brew "zsh"
brew "teamookla/speedtest/speedtest"
cask "arc"
cask "battery"
cask "bitwarden"
cask "blackhole-2ch"
cask "blender"
cask "blockbench"
cask "calibre"
cask "fig"
cask "firefox"
cask "firefox-nightly"
cask "font-twitter-color-emoji"
cask "hiddenbar"
cask "iina"
cask "imageoptim"
cask "iterm2"
cask "krita"
cask "maccy"
cask "obsidian"
cask "open-in-code"
cask "openemu"
cask "openra"
cask "prism"
cask "raycast"
cask "rectangle"
cask "sengi"
cask "shottr"
cask "standard-notes"
cask "temurin17"
cask "vlc"
cask "zulu8"
mas "Amphetamine", id: 937984704
mas "Backtrack", id: 1477089520
mas "Color Picker", id: 1545870783
mas "DevCleaner", id: 1388020431
mas "Hand Mirror", id: 1502839586
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Microsoft PowerPoint", id: 462062816
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Prime Video", id: 545519333
mas "Shorui", id: 1448111859
mas "Sugarmate", id: 1207352056
mas "Tandem Device Updater", id: 1100870281
mas "TestFlight", id: 899247664
mas "Vectornator", id: 1219074514
mas "Yoink", id: 457622435
